In [ ]:
!pip install pandas

In [ ]:
import pandas as pd
data=[1,2,3,4,5]
s=pd.Series(data)
print(s)

In [ ]:
import pandas as pd
'''creation of series using dictionary'''
data={'a':10,'b':20,'c':30}
s=pd.Series(data)
print(s)

In [43]:
import pandas as pd
'''another way to create a series'''
data=[1,2,3]
index=["a","b","c"]
s=pd.Series(data,index=index)
print(s)

a    1
b    2
c    3
dtype: int64

In [ ]:
'''dataframe is 2d array having rows and columns it is a collection of series'''
import pandas as pd
data={"name":["abc","def","ghi"],
      "age":[20,21,22],
      "city":["pune","mumbai","delhi"]}
df=pd.DataFrame(data)
print(df)

In [ ]:
'''in array form'''
import numpy as np
np.array(df)

In [3]:
'''creation of dataframe from list of dictionaries'''
import pandas as pd
data=[{"name":"abc","age":20,"city":"pune"},
      {"name":"def","age":21,"city":"mumbai"}]
df=pd.DataFrame(data)
print(df)

  name  age    city
0  abc   20    pune
1  def   21  mumbai

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('data.csv')
print(df)

               Date Category  Value    Product  Sales Region
0        25-01-2006        A     99   Product2    599   West
1        16-01-2023        B    100   Product3    938  South
2   17 January 2023        B     97   Product4    900   East
3        18-01-2023        C     94   Product5    905  North
4        19-01-2023        B     98   Product6    910   East
5        20-01-2023        B     97   Product7    400   West
6        21-01-2023        C     99   Product8    500  South
7        22-01-2023        B     96   Product9    600  North
8        23-01-2023        B      1  Product10    100   East
9        24-01-2023        A      5  Product11    110  North
10       25-01-2023        B      9  Product12    200   West
11       26-01-2023        C     99  Product13    300  South
12       27-01-2023        B     80  Product14    400   East
13       28-01-2023        B     88  Product15    550  North
14       29-01-2023        B     99  Product16    650  South
15       30-01-2023        A     89  Product17    700  North
16       31-01-2023        C     99  Product18    810   East
17       01-02-2023        A     99  Product19    900   West
18       02-02-2023        B     87  Product20    999   East
19       03-02-2023        B     99  Product21    400   West
20       04-02-2023        C     99  Product22    200  South
21       05-02-2023        B     99  Product23    300  North
22       06-02-2023        A     99  Product24    400  South
23       07-02-2023        B     97  Product25    500   East
24       08-02-2023        A     99  Product26    600  South
25       09-02-2023        B     97  Product27    700  South
26       10-02-2023        B     99  Product28    800   West
27       11-02-2023        C     98  Product29    900  South
28       12-02-2023        B     99  Product30    999   East
29       13-02-2023        A     91  Product31   1000  North
30       14-02-2023        C     99  Product32   1000  South

In [6]:
df.tail(5)

          Date Category  Value    Product  Sales Region
26  10-02-2023        B     99  Product28    800   West
27  11-02-2023        C     98  Product29    900  South
28  12-02-2023        B     99  Product30    999   East
29  13-02-2023        A     91  Product31   1000  North
30  14-02-2023        C     99  Product32   1000  South

In [7]:
df.describe()

            Value        Sales
count   31.000000    31.000000
mean    87.419355   621.612903
std     27.824179   287.314656
min      1.000000   100.000000
25%     92.500000   400.000000
50%     98.000000   600.000000
75%     99.000000   900.000000
max    100.000000  1000.000000

In [8]:
df.head(5)

              Date Category  Value   Product  Sales Region
0       25-01-2006        A     99  Product2    599   West
1       16-01-2023        B    100  Product3    938  South
2  17 January 2023        B     97  Product4    900   East
3       18-01-2023        C     94  Product5    905  North
4       19-01-2023        B     98  Product6    910   East

In [9]:
df.dtypes

Date        object
Category    object
Value        int64
Product     object
Sales        int64
Region      object
dtype: object

In [ ]:
'''Handling missing values'''
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False  False   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False  False    False  False   False
16  False     False  False    False  False   False
17  False     False  False    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False  False    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False

In [9]:
import pandas as pd
df=pd.read_csv('data.csv')
df.isnull()
'''if there is blank space between commas then it will not consider that as null value'''

     Date  Category  Value  Product  Sales  Region
0    True      True  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False   True    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False  False   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False  False    False  False   False
16  False     False  False    False  False   False
17  False     False  False    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False  False    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False

In [4]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region       True
dtype: bool

In [10]:
df.isnull().sum()
'''it will return total number of null values in each column'''

Date        1
Category    1
Value       1
Product     0
Sales       0
Region      0
dtype: int64

In [16]:
'''filling missing values '''
df.fillna(0)
df['sales_fillNA'] = df['Value'].fillna(df['Value'].mean())
print(df)

               Date Category  Value    Product  Sales Region  sales_fillNA
0               NaN      NaN   99.0   Product2    599   West          99.0
1        16-01-2023        B  100.0   Product3    938  South         100.0
2   17 January 2023        B   97.0   Product4    900   East          97.0
3        18-01-2023        C    NaN   Product5    905  North          87.2
4        19-01-2023        B   98.0   Product6    910   East          98.0
5        20-01-2023        B   97.0   Product7    400   West          97.0
6        21-01-2023        C   99.0   Product8    500  South          99.0
7        22-01-2023        B   96.0   Product9    600  North          96.0
8        23-01-2023        B    1.0  Product10    100   East           1.0
9        24-01-2023        A    5.0  Product11    110  North           5.0
10       25-01-2023        B    9.0  Product12    200   West           9.0
11       26-01-2023        C   99.0  Product13    300  South          99.0
12       27-01-2023        B   80.0  Product14    400   East          80.0
13       28-01-2023        B   88.0  Product15    550  North          88.0
14       29-01-2023        B   99.0  Product16    650  South          99.0
15       30-01-2023        A   89.0  Product17    700  North          89.0
16       31-01-2023        C   99.0  Product18    810   East          99.0
17       01-02-2023        A   99.0  Product19    900   West          99.0
18       02-02-2023        B   87.0  Product20    999   East          87.0
19       03-02-2023        B   99.0  Product21    400   West          99.0
20       04-02-2023        C   99.0  Product22    200  South          99.0
21       05-02-2023        B   99.0  Product23    300  North          99.0
22       06-02-2023        A   99.0  Product24    400  South          99.0
23       07-02-2023        B   97.0  Product25    500   East          97.0
24       08-02-2023        A   99.0  Product26    600  South          99.0
25       09-02-2023        B   97.0  Product27    700  South          97.0
26       10-02-2023        B   99.0  Product28    800   West          99.0
27       11-02-2023        C   98.0  Product29    900  South          98.0
28       12-02-2023        B   99.0  Product30    999   East          99.0
29       13-02-2023        A   91.0  Product31   1000  North          91.0
30       14-02-2023        C   99.0  Product32   1000  South          99.0

In [49]:
'''renaming columns'''
import pandas as pd
df=pd.read_csv('data.csv')
df=df.rename(columns={'Date':'sales__date'})
df.head()

       sales__date Category  Value   Product  Sales Region
0              NaN      NaN   99.0  Product2    599   West
1       16-01-2023        B  100.0  Product3    938  South
2  17 January 2023        B   97.0  Product4    900   East
3       18-01-2023        C    NaN  Product5    905  North
4       19-01-2023        B   98.0  Product6    910   East

In [53]:
###changing data types
df.dtypes
df['NEW_value']=df['Value'].fillna(df['Value'].mean()).astype(int)
print(df)

        sales__date Category  Value    Product  Sales Region  NEW_value
0               NaN      NaN   99.0   Product2    599   West         99
1        16-01-2023        B  100.0   Product3    938  South        100
2   17 January 2023        B   97.0   Product4    900   East         97
3        18-01-2023        C    NaN   Product5    905  North         87
4        19-01-2023        B   98.0   Product6    910   East         98
5        20-01-2023        B   97.0   Product7    400   West         97
6        21-01-2023        C   99.0   Product8    500  South         99
7        22-01-2023        B   96.0   Product9    600  North         96
8        23-01-2023        B    1.0  Product10    100   East          1
9        24-01-2023        A    5.0  Product11    110  North          5
10       25-01-2023        B    9.0  Product12    200   West          9
11       26-01-2023        C   99.0  Product13    300  South         99
12       27-01-2023        B   80.0  Product14    400   East         80
13       28-01-2023        B   88.0  Product15    550  North         88
14       29-01-2023        B   99.0  Product16    650  South         99
15       30-01-2023        A   89.0  Product17    700  North         89
16       31-01-2023        C   99.0  Product18    810   East         99
17       01-02-2023        A   99.0  Product19    900   West         99
18       02-02-2023        B   87.0  Product20    999   East         87
19       03-02-2023        B   99.0  Product21    400   West         99
20       04-02-2023        C   99.0  Product22    200  South         99
21       05-02-2023        B   99.0  Product23    300  North         99
22       06-02-2023        A   99.0  Product24    400  South         99
23       07-02-2023        B   97.0  Product25    500   East         97
24       08-02-2023        A   99.0  Product26    600  South         99
25       09-02-2023        B   97.0  Product27    700  South         97
26       10-02-2023        B   99.0  Product28    800   West         99
27       11-02-2023        C   98.0  Product29    900  South         98
28       12-02-2023        B   99.0  Product30    999   East         99
29       13-02-2023        A   91.0  Product31   1000  North         91
30       14-02-2023        C   99.0  Product32   1000  South         99

In [56]:
df['modified_value']=df['Value'].apply(lambda x:x*2)
print(df)

        sales__date Category  Value    Product  Sales Region  NEW_value  \
0               NaN      NaN   99.0   Product2    599   West         99
1        16-01-2023        B  100.0   Product3    938  South        100
2   17 January 2023        B   97.0   Product4    900   East         97
3        18-01-2023        C    NaN   Product5    905  North         87
4        19-01-2023        B   98.0   Product6    910   East         98
5        20-01-2023        B   97.0   Product7    400   West         97
6        21-01-2023        C   99.0   Product8    500  South         99
7        22-01-2023        B   96.0   Product9    600  North         96
8        23-01-2023        B    1.0  Product10    100   East          1
9        24-01-2023        A    5.0  Product11    110  North          5
10       25-01-2023        B    9.0  Product12    200   West          9
11       26-01-2023        C   99.0  Product13    300  South         99
12       27-01-2023        B   80.0  Product14    400   East         80
13       28-01-2023        B   88.0  Product15    550  North         88
14       29-01-2023        B   99.0  Product16    650  South         99
15       30-01-2023        A   89.0  Product17    700  North         89
16       31-01-2023        C   99.0  Product18    810   East         99
17       01-02-2023        A   99.0  Product19    900   West         99
18       02-02-2023        B   87.0  Product20    999   East         87
19       03-02-2023        B   99.0  Product21    400   West         99
20       04-02-2023        C   99.0  Product22    200  South         99
21       05-02-2023        B   99.0  Product23    300  North         99
22       06-02-2023        A   99.0  Product24    400  South         99
23       07-02-2023        B   97.0  Product25    500   East         97
24       08-02-2023        A   99.0  Product26    600  South         99
25       09-02-2023        B   97.0  Product27    700  South         97
26       10-02-2023        B   99.0  Product28    800   West         99
27       11-02-2023        C   98.0  Product29    900  South         98
28       12-02-2023        B   99.0  Product30    999   East         99
29       13-02-2023        A   91.0  Product31   1000  North         91
30       14-02-2023        C   99.0  Product32   1000  South         99

    modified_value
0            198.0
1            200.0
2            194.0
3              NaN
4            196.0
5            194.0
6            198.0
7            192.0
8              2.0
9             10.0
10            18.0
11           198.0
12           160.0
13           176.0
14           198.0
15           178.0
16           198.0
17           198.0
18           174.0
19           198.0
20           198.0
21           198.0
22           198.0
23           194.0
24           198.0
25           194.0
26           198.0
27           196.0
28           198.0
29           182.0
30           198.0

In [57]:
##Data aggregating and grouping
df.head()

,sales__date,Category,Value,Product,Sales,Region,NEW_value,modified_value
0,NaN,NaN,99.0,Product2,599,West,99,198.0
1,16-01-2023,B,100.0,Product3,938,South,100,200.0
2,17 January 2023,B,97.0,Product4,900,East,97,194.0
3,18-01-2023,C,NaN,Product5,905,North,87,NaN
4,19-01-2023,B,98.0,Product6,910,East,98,196.0

In [59]:
grouped_mean=df.groupby('Category')['Value'].mean()
print(grouped_mean)

Category
A    80.333333
B    84.823529
C    98.833333
Name: Value, dtype: float64

In [61]:
df.groupby(['Category','Region'])['Value'].sum()

Category  Region
A         North     185.0
          South     198.0
          West       99.0
B         East      559.0
          North     283.0
          South     296.0
          West      304.0
C         East       99.0
          North       0.0
          South     494.0
Name: Value, dtype: float64

In [63]:
##aggregate multiple functions
grouped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
print(grouped_agg)

             mean    sum  count
Region
East    82.250000  658.0      8
North   78.000000  468.0      6
South   98.800000  988.0     10
West    83.666667  502.0      6

In [64]:
###merging and joining dataframes
df1=pd.DataFrame({'key':['A','B','C'],'value1':[1,2,3]})
df2=pd.DataFrame({'key':['A','B','D'],'value2':[4,5,6]})

In [66]:
df1

  key  value2
0   A       4
1   B       5
2   D       6

In [67]:
df2

  key  value2
0   A       4
1   B       5
2   D       6

In [68]:
''''merging of two dataframes on key column'''
pd.merge(df1, df2, how='inner', on='key')

  key  value1  value2
0   A       1       4
1   B       2       5

In [69]:
pd.merge(df1,df2,how='outer',on='key')

  key  value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [70]:
pd.merge(df1,df2,how='left',on='key')

  key  value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [71]:
pd.merge(df1,df2,how='right',on='key')###right dataframe will be given priority

  key  value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [73]:
'''Reading data from various data sources'''
import pandas as pd
from io import StringIO
data='{"employee_name":"sanu","email":"avinashmadhu78@gmail.com","job-profile":[{"title1":"Team Lead","title2":"project manager"}]}'###data in th form of json
df=pd.read_json(StringIO(data))###converted into dataframe

In [74]:
df

,employee_name,email,job-profile
0,sanu,avinashmadhu78@gmail.com,"{'title1': 'Team Lead', 'title2': 'project man..."

In [75]:
df.to_json()

'{"employee_name":{"0":"sanu"},"email":{"0":"avinashmadhu78@gmail.com"},"job-profile":{"0":{"title1":"Team Lead","title2":"project manager"}}}'

In [76]:
df.to_json(orient='index')

'{"0":{"employee_name":"sanu","email":"avinashmadhu78@gmail.com","job-profile":{"title1":"Team Lead","title2":"project manager"}}}'

In [77]:
df.to_json(orient='records')

'[{"employee_name":"sanu","email":"avinashmadhu78@gmail.com","job-profile":{"title1":"Team Lead","title2":"project manager"}}]'

In [88]:
%pip install lxml
%pip install beautifulsoup4

Requirement already satisfied: lxml in c:\python\.venv\lib\site-packages (6.0.4)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.3-py3-none-any.whl (37 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, soupsieve, beautifulsoup4

   ------------- -------------------------- 1/3 [soupsieve]
   -------------------------- ------------- 2/3 [beautifulsoup4]
   -------------------------- ------------- 2/3 [beautifulsoup4]
   -------------------------- ------------- 2/3 [beautifulsoup4]
   ---------------------------------------- 3/3 [beautifulsoup4]

Successfully installed beautifulsoup4-4.14.3 soupsieve-2.8.3 typing-extensions-4.15.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [86]:
%pip install html5Lib

Collecting html5Lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\python\.venv\lib\site-packages (from html5Lib) (1.17.0)
Collecting webencodings (from html5Lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, html5Lib

   ---------------------------------------- 0/2 [webencodings]
   -------------------- ------------------- 1/2 [html5Lib]
   -------------------- ------------------- 1/2 [html5Lib]
   -------------------- ------------------- 1/2 [html5Lib]
   -------------------- ------------------- 1/2 [html5Lib]
   ---------------------------------------- 2/2 [html5Lib]

Successfully installed html5Lib-1.1 webencodings-0.5.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [108]:


url="https://www.fdic.gov/bank-failures/failed-bank-list"
df=pd.read_html(url)
print(df)

[                                            Bank Name                City  \
0                   Metropolitan Capital Bank & Trust             Chicago
1                        The Santa Anna National Bank          Santa Anna
2                                Pulaski Savings Bank             Chicago
3                  The First National Bank of Lindsay             Lindsay
4               Republic First Bank dba Republic Bank        Philadelphia
5                                       Citizens Bank            Sac City
6                            Heartland Tri-State Bank             Elkhart
7                                 First Republic Bank       San Francisco
8                                      Signature Bank            New York
9                                 Silicon Valley Bank         Santa Clara
10                                  Almena State Bank              Almena
11                         First City Bank of Florida   Fort Walton Beach
12                               The First State Bank       Barboursville
13                                 Ericson State Bank             Ericson
14                   City National Bank of New Jersey              Newark
15                                      Resolute Bank              Maumee
16                              Louisa Community Bank              Louisa
17                               The Enloe State Bank              Cooper
18                Washington Federal Bank for Savings             Chicago
19    The Farmers and Merchants State Bank of Argonia             Argonia
20                                Fayette County Bank          Saint Elmo
21  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
22                                     First NBC Bank         New Orleans
23                                      Proficio Bank  Cottonwood Heights
24                      Seaway Bank and Trust Company             Chicago

            State   Cert                Acquiring Institution  \
0        Illinois  57488              First Independence Bank
1           Texas   5520            Coleman County State Bank
2        Illinois  28611                      Millennium Bank
3        Oklahoma   4134               First Bank & Trust Co.
4    Pennsylvania  27332    Fulton Bank, National Association
5            Iowa   8758            Iowa Trust & Savings Bank
6          Kansas  25851               Dream First Bank, N.A.
7      California  59017            JPMorgan Chase Bank, N.A.
8        New York  57053                  Flagstar Bank, N.A.
9      California  24735  First–Citizens Bank & Trust Company
10         Kansas  15426                          Equity Bank
11        Florida  16748            United Fidelity Bank, fsb
12  West Virginia  14361                       MVB Bank, Inc.
13       Nebraska  18265           Farmers and Merchants Bank
14     New Jersey  21111                      Industrial Bank
15           Ohio  58317                   Buckeye State Bank
16       Kentucky  58112    Kentucky Farmers Bank Corporation
17          Texas  10716                   Legend Bank, N. A.
18       Illinois  30570                   Royal Savings Bank
19         Kansas  17719                          Conway Bank
20       Illinois   1802            United Fidelity Bank, fsb
21      Wisconsin  30003  First-Citizens Bank & Trust Company
22      Louisiana  58302                         Whitney Bank
23           Utah  35495                    Cache Valley Bank
24       Illinois  19328                  State Bank of Texas

         Closing Date  Fund  Sort ascending
0    January 30, 2026                 10550
1       June 27, 2025                 10549
2    January 17, 2025                 10548
3    October 18, 2024                 10547
4      April 26, 2024                 10546
5    November 3, 2023                 10545
6       July 28, 2023                 10544
7         May 1, 2023                 10543
8      March 12, 2023                 10540
9      March 10, 2023                 10539
10   October 23, 2020                 10538
11   October 16, 2020                 10537
12      April 3, 2020                 10536
13  February 14, 2020                 10535
14   November 1, 2019                 10534
15   October 25, 2019                 10533
16   October 25, 2019                 10532
17       May 31, 2019                 10531
18  December 15, 2017                 10530
19   October 13, 2017                 10529
20       May 26, 2017                 10528
21        May 5, 2017                 10527
22     April 28, 2017                 10526
23      March 3, 2017                 10525
24   January 27, 2017                 10524  ]

In [103]:
pip install lxml html5lib requests

Requirement already satisfied: lxml in c:\python\.venv\lib\site-packages (6.0.4)
Requirement already satisfied: html5lib in c:\python\.venv\lib\site-packages (1.1)
Collecting requests
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: six>=1.9 in c:\python\.venv\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\python\.venv\lib\site-packages (from html5lib) (0.5.1)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl (159 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.2.25 charset_normalizer-3.4.7 idna-3.11 requests-2.33.1 urllib3-2.6.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [111]:

url="https://www.fdic.gov/bank-failures/failed-bank-list"
pd.read_html(url,match="City",header=0)##in the form of list of dataframes

[                                            Bank Name                City  \
 0                   Metropolitan Capital Bank & Trust             Chicago
 1                        The Santa Anna National Bank          Santa Anna
 2                                Pulaski Savings Bank             Chicago
 3                  The First National Bank of Lindsay             Lindsay
 4               Republic First Bank dba Republic Bank        Philadelphia
 5                                       Citizens Bank            Sac City
 6                            Heartland Tri-State Bank             Elkhart
 7                                 First Republic Bank       San Francisco
 8                                      Signature Bank            New York
 9                                 Silicon Valley Bank         Santa Clara
 10                                  Almena State Bank              Almena
 11                         First City Bank of Florida   Fort Walton Beach
 12                               The First State Bank       Barboursville
 13                                 Ericson State Bank             Ericson
 14                   City National Bank of New Jersey              Newark
 15                                      Resolute Bank              Maumee
 16                              Louisa Community Bank              Louisa
 17                               The Enloe State Bank              Cooper
 18                Washington Federal Bank for Savings             Chicago
 19    The Farmers and Merchants State Bank of Argonia             Argonia
 20                                Fayette County Bank          Saint Elmo
 21  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 22                                     First NBC Bank         New Orleans
 23                                      Proficio Bank  Cottonwood Heights
 24                      Seaway Bank and Trust Company             Chicago

             State   Cert                Acquiring Institution  \
 0        Illinois  57488              First Independence Bank
 1           Texas   5520            Coleman County State Bank
 2        Illinois  28611                      Millennium Bank
 3        Oklahoma   4134               First Bank & Trust Co.
 4    Pennsylvania  27332    Fulton Bank, National Association
 5            Iowa   8758            Iowa Trust & Savings Bank
 6          Kansas  25851               Dream First Bank, N.A.
 7      California  59017            JPMorgan Chase Bank, N.A.
 8        New York  57053                  Flagstar Bank, N.A.
 9      California  24735  First–Citizens Bank & Trust Company
 10         Kansas  15426                          Equity Bank
 11        Florida  16748            United Fidelity Bank, fsb
 12  West Virginia  14361                       MVB Bank, Inc.
 13       Nebraska  18265           Farmers and Merchants Bank
 14     New Jersey  21111                      Industrial Bank
 15           Ohio  58317                   Buckeye State Bank
 16       Kentucky  58112    Kentucky Farmers Bank Corporation
 17          Texas  10716                   Legend Bank, N. A.
 18       Illinois  30570                   Royal Savings Bank
 19         Kansas  17719                          Conway Bank
 20       Illinois   1802            United Fidelity Bank, fsb
 21      Wisconsin  30003  First-Citizens Bank & Trust Company
 22      Louisiana  58302                         Whitney Bank
 23           Utah  35495                    Cache Valley Bank
 24       Illinois  19328                  State Bank of Texas

          Closing Date  Fund  Sort ascending
 0    January 30, 2026                 10550
 1       June 27, 2025                 10549
 2    January 17, 2025                 10548
 3    October 18, 2024                 10547
 4      April 26, 2024                 10546
 5    November 3, 2023                 10545
 6       July 28, 2023                 10544
 7         May 1, 2023                 10543
 8      March 12, 2023                 10540
 9      March 10, 2023                 10539
 10   October 23, 2020                 10538
 11   October 16, 2020                 10537
 12      April 3, 2020                 10536
 13  February 14, 2020                 10535
 14   November 1, 2019                 10534
 15   October 25, 2019                 10533
 16   October 25, 2019                 10532
 17       May 31, 2019                 10531
 18  December 15, 2017                 10530
 19   October 13, 2017                 10529
 20       May 26, 2017                 10528
 21        May 5, 2017                 10527
 22     April 28, 2017                 10526
 23      March 3, 2017                 10525
 24   January 27, 2017                 10524  ]